services:
  shopware:
    image: dockware/dev:latest
    container_name: shopware
    ports:
      - "80:80"
      - "443:443"
      - "3306:3306"
      - "24:24"
      - "8888:8888"
      - "9999:9999"
      - "9998:9998"
    volumes:
      - "db_volume:/var/lib/mysql"
      - "./.docker/mysql:/var/backups/mysql:rw"
      - "./src/.env:/var/www/html/.env:r"
      - "./src/.env.local:/var/www/html/.env.local:r"
      - "./src:/var/www/html:rw"
      - "./.docker/php/php-fix.conf:/etc/php/8.3/fpm/conf.d/php-fix.conf"
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=0
      - PHP_VERSION=8.3

volumes:
  db_volume:
    driver: local

networks:
  web:
    external: false
