services:
  shopware:
    image: dockware/dev:latest
    container_name: shopware
    ports:
      - "80:80"
      - "443:443"
      - "3306:3306"
      - "24:24"
      - "8888:8888"
      - "9999:9999"
      - "9998:9998"
    volumes:
      - "db_volume:/var/lib/mysql"
      - "shop_volume:/var/www/html"
    networks:
      - web
    environment:
      - XDEBUG_ENABLED=0
      - PHP_VERSION=8.3

volumes:
  db_volume:
    driver: local
  shop_volume:
    driver: local

networks:
  web:
    external: false
